# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100)),
                ('email', models.CharField(error_messages={'max_length': 'You cant add more than 50 characters'}, max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100)),
                ('status', models.CharField(error_messages={'max_length': 'You cant add more than 50 characters'}, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
