# Generated by Django 4.0.3 on 2022-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gas_bill', models.CharField(max_length=100)),
                ('security_bill', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
