# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        ('unit', '0001_initial'),
        ('branch', '0001_initial'),
        ('month', '0001_initial'),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=200)),
                ('nid', models.CharField(max_length=200)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rent_pm', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('floor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floor.floor')),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
