# Generated by Django 4.0.3 on 2022-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
