# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100)),
                ('description', models.CharField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100)),
                ('date', models.CharField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100)),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
