# Generated by Django 4.0.3 on 2022-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateField(error_messages={'max_length': 'You cant add more than 100 characters'}, max_length=100),
        ),
    ]
