# Generated by Django 4.0.3 on 2022-03-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'All Bill', 'verbose_name_plural': 'Alll Bills'},
        ),
    ]
