# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('month', '0001_initial'),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
