# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('securityGuardMobile', models.CharField(max_length=200)),
                ('secratatyMobile', models.CharField(max_length=200)),
                ('moderatorMobile', models.CharField(max_length=200)),
                ('buildingMakeYear', models.CharField(max_length=200)),
                ('b_name', models.CharField(max_length=200)),
                ('b_address', models.CharField(max_length=200)),
                ('b_phone', models.CharField(max_length=200)),
                ('buildingImage', models.ImageField(upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
