# Generated by Django 4.0.3 on 2022-03-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        ('unit', '0001_initial'),
        ('branch', '0001_initial'),
        ('month', '0001_initial'),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('rid', models.CharField(max_length=100)),
                ('water_bill', models.CharField(max_length=100)),
                ('electric_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gas_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('security_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utility_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issue_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('floor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floor.floor')),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
